# spring boot management server instance properties
spring:
  application:
    name: hakikisha-details
  profiles:
    active: dev

#API Authentication
  security: 
    user: 
      name: admin
      password: password
      roles: USER
      
info:
  app:
    name: hakikisha-details
    description: This service will obtain various  viz., customer details from accounts, mobile wallets etc. This will be a generic interface for any future hakikisha service
    version: 1.0.0
    
pod:
  name: hakikisha-details
  
#management:
  #server:
    #port: 8082
  #endpoints: 
    #web: 
      #exposure: 
        #include: '*'
    
server:
  port: 8087
  
redis:
  serviceName: localhost
  servicePort: 6391
  maxActive: 50
  maxIdle: 40
  minIdle: 10
  blockWhenExhausted: true
  maxWaitSeconds: 2
  minEvictableIdleTimeSeconds: 120
  timeBetweenEvictionRunsSeconds: 60
  testOnBorrow: false
  testWhileIdle: true
  password:
  timeOutSeconds: 1
  expireSeconds: 120
#logging configuration path
logging:
  config: classpath:logback.xml
  
#pesalink endpoints details  
pesalink:
  account:
    hostUrl: http://172.16.17.25:20004/api/v1/pesalink/verification
    login: admin
    password: admin
    requestPayloadFilePath: /hakikisha/pesalink_account_req.json
  mobile: 
    hostUrl: http://172.17.152.67:8527/kba/webservices/v2/LookupDbWS
    login: KCB
    password: 123456
    requestPayloadFilePath: /hakikisha/pesalink_mobile_req.xml
    transactionCost: 0
    
#daraja endpoints details 161
daraja: 
  hostUrl: http://172.16.21.118:8085/KcbDaraja/DarajaAPI
  login: ESbuser001
  password: ESBuXer#2@19121Ui
  requestPayloadFilePath: /hakikisha/daraja_account_req.xml
  ServiceId: 3
  BillerId: 1
  MessageTypeIndicator: 0200
  CompanyId: KE0010001
  ChannelId: 10
  transactionCost: 0

#mpesa agent endpoints details
mpesa: 
  agent: 
    hostUrl: https://172.17.74.214:7846/API/getAgentData
    requestPayloadFilePath: /hakikisha/mpesa_agent_req.json
    systemCode: 043
    password: MTIzNDU2MDAwMDAwMDAwMAe9OjBVvr9lI23fygLnlZmsC0Jl/rESOQoibMKI6GgmT0duDYYH/43QGkJye3KF0g==
    transactionCost: 0




